{% set name = "mapbox_earcut" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f155e429a22e27387cfd7a6372c3a3865aafa609ad725e2c4465257f154a438

build:
  number: 1
  script: "{{ PYTHON }} -m pip install -vv ."

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
    - pybind11
    - pip
    - setuptools
    - numpy >=2
  run:
    - python >=3.9

test:
  requires:
    - pytest

  imports:
    - mapbox_earcut

  files:
    - test_earcut.py

  commands:
    - pytest test_earcut.py

about:
  home: https://github.com/skogler/mapbox_earcut_python
  license: "ISC AND BSD-3-Clause"
  license_file:
    - LICENSE.md
    - include/mapbox/LICENSE
  summary: "Python version of Mapbox Earcut library: fast and quite robust triangulation of 2D polygons."
  description: |
    The library implements a modified ear slicing algorithm, optimized by z-order
    curve hashing and extended to handle holes, twisted polygons, degeneracies and
    self-intersections in a way that doesn't guarantee correctness of triangulation,
    but attempts to always produce acceptable results for practical data like
    geographical shapes.
  dev_url: https://github.com/skogler/mapbox_earcut_python

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - jay-hennen
