{% set name = "mapbox_earcut" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 997ab14b9afbc14b1aede880b8f57efc7f28d6811a08db0adf1804b63bab0d9b

# leaving these in in case we still need something like that for Windows
#  patches:
#    - 0002-removed-A-flag-for-Windows-builds.patch
#    - 0003-further-removed-m-option.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install -vv ."

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pybind11
  run:
    - python
    - numpy

test:
  imports:
    - mapbox_earcut

about:
  home: https://github.com/skogler/mapbox_earcut_python
  license: "ISC AND BSD-3-Clause"
  license_file:
    - LICENSE.md
    - include/mapbox/LICENSE
  summary: "Python version of Mapbox Earcut library: fast and quite robust triangulation of 2D polygons."
  description: |
    The library implements a modified ear slicing algorithm, optimized by z-order
    curve hashing and extended to handle holes, twisted polygons, degeneracies and
    self-intersections in a way that doesn't guarantee correctness of triangulation,
    but attempts to always produce acceptable results for practical data like
    geographical shapes.
  dev_url: https://github.com/skogler/mapbox_earcut_python

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - jay-hennen
